### ISSUE TITLE
query FOM for the time-discrete residual

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#15]
This feature seems to be useful for a few cases. 

- [x] List feasibility and limitations (e.g does this seamlessly apply to ST, TC-LSRM and other ROMs?)
- [x] create/finalize a tentative design plan
- [x] identify which steps are the main bottlenecks 
- [x] identify main challenges of integrating the design into pressio 
- [x] draft an implementation inside an `experimental` namespace inside pressio/rom
- [x] create unit tests
- [x] create regular tests
- [x] move functionality into main namespace

**Comment by fnrizzi** [comment]
@vbrunini as discussed, we are going to enable pressio to support querying the application/full-order model (FOM) for the **time-discrete residual** directly, rather than querying the velocity only.
So, i am trying to gather information about what you would prefer the new method to be. 
For the velocity, we have something like: 
```c++
void velocity( const state_t & x, scalar_t time, velocity_t f) const;
velocity_t velocity( const state_t & x, scalar_t time) const;
```
Please note that here the FOM state is owned by pressio because (a) I need to reconstruct it from the ROM state; and (b) the FOM should not know anything about ROM. 

We need something similar for the time-discrete residual. 
```c++
void timeDiscreteResidua( *something*, scalar_t time, residual_t f) const;
residual_t timeDiscreteResidua( const state_t & x, scalar_t time) const;
```
Some things to think about: 
* This new interface should be unaware of the time stepper used. So it should work for anything. 
The interface should forward args to a sutiable implementation that knows about time stepping. 
* who owns the FOM states at current time, `x_n`, and previous time step `x_nm1`? 
The app definitely has to. Also, we need to consider that these need to be reconstructed by pressio. So if pressio owns them, I need to pass them to you so maybe a variadic method would work in that case. 

Do you have any thoughts?

**Comment by pjb236** [comment]
I think this is exactly what is needed for the thermal solver in SPARC as it is currently implemented.

**Comment by fnrizzi** [comment]
@eparish1 @pjb236 for TC-LSRM we need the time-discrete Jacobian wrt all the states

**Comment by fnrizzi** [comment]
@vbrunini we need to talk about who is in charge of the time step... I am thinking now the following: 
- for cases where you want to do integration with uniform time step, pressio owns it and it gives it to you 
- for cases where you might have variable time step, the user can provide it with a functor or lambda (or something else TBD) 
what do you think? Let's talk about this during next meeting

**Comment by fnrizzi** [comment]
#26

**Comment by fnrizzi** [comment]
#26

**Comment by fnrizzi** [comment]
The adapter class for this API looks like this: https://github.com/Pressio/pressio/wiki/Adapter-residual-based-API-for-LSPG
