### ISSUE TITLE
rom: add support for WLS

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#6]
Implement WLS inside pressio/rom

We have added support for WLS in Pressio. We currently support Eigen datatypes, explicit Euler, BDF1, and BDF2. We do not support other datatypes or preconditioning yet.

We are working on adding:

- [ ] Support for Kokkos
- [ ] Increased number of unit tests
- [ ] Support for hyper reduction
- [ ] Support for preconditioning
- [ ] Support for parallel in time over each window
- [ ] Support for QR solution technique
- [ ] (Maybe) Support for block Jacobi

**Comment by eparish1** [comment]
For WLS we have identified the need to add support to the following functionalities:

- [x] (#50) Add functionality for accessing a single column of a mulivector. This is required for being able to store the WLS state as a multivector, in which case we would need to access individual columns to compute things like the residual and Jacobian.  

- [x] (#45) Add functionality for a new Gauss-Newton solver that requires the main operations computeHessian and computeGradient. This is required for an efficient implementation of WLS as it is extremely inefficient to compute the hessian via H = J^T J; instead we need have working variables that are much smaller than J. These working variables are used to incrementally compute H.


- [ ] (#53) Add functionality for accessing and operating on subblocks of a pressio::containers::Matrix. This is required for assembling the Jacobian of the windowed residual. For example, for implicit Euler the algorithm to evaluate the Jacobian looks like

```
#input yROM_window  which is of size (romSize,numStepsInWindow)
#input yROM_IC which is of size (romSize)

H = np.zeros((romSize*numStepsInWindow,romSize*numStepsInWindow)) #this will be a banded block matrix
J1tmp = np.zeros((fomSize*numStepsInWindow,romSize*numStepsInWindow))
J2tmp = np.zeros((fomSize*numStepsInWindow,romSize*numStepsInWindow))

for n in range(0,numStepsInWindow):
  yROM_current = yROM_window[n]
  if (n ==0):
     yROM_past = yROM_IC
  else:
    yROM_past = yROM_window[n-1] 
  J1tmp = computeLocalJacobian(yROM_current,yROM_past,0) #compute dR/dyROM_current
  J2tmp = computeLocalJacobian(yROM_current,yROM_past,1)#compute dR/dyROM_past
  H[n*romSize:(n+1)*romSize,n*romSize:(n+1)*romSize] = np.dot(J2tmp.transpose() ,J1tmp)
  # similar operations for off diagonal terms.
```
We need the functionality for the JW = J2^T J1 step. 

- [ ] (#58) Add an iterator to the auxStatesContainer class. It is extremely advantageous for having a way for us to loop through and update all members. of the fomStatesContainer. For example, suppose we are looping through the steps in the window, and have the relevant states in a fomContainer of size time_stencil_size. As we move from one step to the next, we want to perform the operation:
```
for (int i=0; i < time_stencil_size - 1; i++){
  *fomStateContainerObj_[i].data() = *fomStateContainerObj_[i+1].data();}
const auto wlsCurrentState = wlsState.viewColumnVector(n);
fomStateReconstrObj_(wlsCurrentState,fomStateContainerObj_[time_stencil_size-1]);
  
```
Currently, there is no way to access auxStatesContainer in this way; as a result we would have to rewrite this code for each time stencil size.

- [ ] (#54)  Add functionality for dotting two multi vectors together. This is related to issue #53, where we need to the operation:

`  H[n*romSize:(n+1)*romSize,n*romSize:(n+1)*romSize] = np.dot(J2tmp.transpose() ,J1tmp )`

Presently in Pressio, there is not a way to compute the operation np.dot(J2tmp.transpose() ,J1tmp ) if J1 and J2 are multi vectors. This functionality should be supported for multi vectors, as Pressio does have functionality for computing np.dot(J1tmp.transpose() ,J1tmp).

**Comment by fnrizzi** [comment]
@eparish1 
I have #53 and #54 working for Eigen. See 58bec42678289f95ccff150abf626e923b0ef542
Please merge develop into WLS.

**Comment by fnrizzi** [comment]
@eparish1 
1. can you please update the description of this issue? so that we have something updated that reflects what is inside the code. 
2. also, please delete old wls branches since all is develop now 
3. to move on to Kokkos, please create a new branch
4. when you commit things that pertain this issue, please start the commits with: 
```
 #6: bla blas 
```
