### ISSUE TITLE
rom: enable support for linear space-time ROMs

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#8]
Enable support for linear space-time ROMs inside pressio/rom. 
This should reuse the preliminary work that Chi did in FY19, see #9 

- [ ] create/finalize a tentative design plan
- [ ] identify which steps are the main bottlenecks 
- [ ] identify main challenges of integrating the design into pressio 
- [ ] draft an implementation inside an `experimental` namespace inside pressio/rom
- [ ] create unit tests
- [ ] create regular tests
- [ ] move functionality into main namespace
